# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update``
deps = {
    "torch": "torch==2.1.0",
    "torchvision": "torchvision==0.16",
    "torchaudio": "torchaudio==2.1.0",
    "diagrams": "diagrams==0.20.0",
    "optuna": "optuna==3.0.0",
    "pydantic": "pydantic==1.10.3",
    "filterpy": "filterpy==1.4.5",
    "transformers": "transformers==4.35.1",
    "datasets": "datasets==2.14.6",
    "accelerate": "accelerate==0.24.1",
    "PyGObject": "PyGObject==3.40.1",
    "pytest": "pytest==6.2.5",
}
